### ISSUE TITLE
linkUserWithOauthProvider is not very safe and crashes

### ISSUE THREAD

**Issue by DavidCorrado** [tryVital/vital-android#67]
So linkUserWithOauthProvider if you look at the implementation only catches IOException.  
https://github.com/tryVital/vital-android/blob/e11b7a607249e749abc55aff5bac0eb6318132e8/VitalClient/src/main/java/io/tryvital/client/services/VitalClientExtension.kt#L30
Which is basically internet failures.  So if the service returns any error then this will crash.  

You would think you could just catch Exception but that actually has a problem with coroutine cancellation.  You can do something like this
https://medium.com/androiddevelopers/cancellation-in-coroutines-aa6b90163629
Or like this
https://github.com/android/nowinandroid/blob/151f877bbe6546c78f8f03f16e56564e285fb508/core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/SyncUtilities.kt#L57

Also might want to put the try catch just around the network requests.  Also CustomChrome tabs can also throw a ActivityNotFoundException on phones without a browser so thats another potential issue with just wrapping it around the network requests.

This is just an extension function so not a big deal as we can work around by just writing our own extension function

**Comment by andersio** [comment]
Yeah. Wasn't sure why it was chosen to return a `Result`.

In this particular scenario, all exceptions can left unhandled and propagate to the caller, and letting the caller to decide what to deal with them, especially since the routine itself doesn't really have any side effect responding to any specific exception. 

Most probably I will mark this as deprecated and create a new version that is simply `suspend (...Args) -> Unit`.

**Comment by andersio** [comment]
The replacement has been released.
